sigma = 10;
beta = 8.1/3;
rho = 28;
lorenz = @(t,a) [-sigma*a(1) + sigma*a(2); rho*a(1) - a(2) - a(1)*a(3); -beta*a(3) + a(1)*a(2)];
options = odeset('RelTol',1e-7,'AbsTol',1e-7);
h1=figure;
[t,ya] = ode45(lorenz,[0,100],[10,20,30],options);
plot(ya(:,1),ya(:,3));  
xlabel('$x$','Interpreter','LaTeX','FontSize',20); 
ylabel('$z$','Interpreter','LaTeX','FontSize',20);
plot3(ya(:,1),ya(:,2),ya(:,3));
azimuth = -76;  
elevation = -40;
view(azimuth,elevation);
xlabel('$x$','Interpreter','LaTeX','FontSize',20);
ylabel('$y$','Interpreter','LaTeX','FontSize',20);
zlabel('$z$','Interpreter','LaTeX','FontSize',20);
view(90,0);
view(0,90);
view(0,0);
h3 = figure;
plot(t(1:5000),ya([1:5000],1));
xlabel('$t$ (seconds)','Interpreter','LaTeX','FontSize',20);
ylabel('$x$','Interpreter','LaTeX','FontSize',20);